import Link from 'next/link'
import { ArrowRight, BookOpen, FileText, Globe2, Quote } from 'lucide-react'
import { ArchiveShell, Eyebrow, Rule } from '@/components/archive-shell'

const features = [
  ['1936', 'Annihilation of Caste', 'The defining text on caste, equality, and the work of social reform.', '/manuscript/annihilation-of-caste'],
  ['1949', 'Constitutional Debates', 'Notes and speeches from the making of a democratic republic.', '/archive'],
  ['1956', 'The Buddha and His Dhamma', 'A final work on ethics, reason, and human dignity.', '/manuscript/the-buddha-and-his-dhamma'],
]

export default function Home() {
  return <ArchiveShell><main>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.1fr_0.9fr] lg:px-8 lg:pb-28 lg:pt-24">
      <div className="flex flex-col justify-center"><Eyebrow>A living digital archive · 1891—1956</Eyebrow><h1 className="mt-5 max-w-4xl text-6xl font-semibold leading-[0.92] tracking-[-0.075em] text-balance sm:text-8xl">Read the ideas that made modern India.</h1><p className="mt-7 max-w-xl text-base leading-7 text-muted-foreground">Explore the writings, speeches, and manuscripts of Dr. B. R. Ambedkar—preserved, searchable, and made legible for a new generation.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/archive" className="flex items-center gap-3 bg-primary px-5 py-3 text-sm font-bold text-primary-foreground transition-transform hover:-translate-y-0.5">Enter the archive <ArrowRight size={16} /></Link><Link href="/biography" className="flex items-center gap-2 border border-foreground/20 px-5 py-3 text-sm font-semibold transition-colors hover:border-primary">Meet Ambedkar</Link></div></div>
      <div className="relative flex min-h-[430px] items-end overflow-hidden bg-primary p-7 text-primary-foreground sm:p-10"><div className="absolute inset-0 opacity-25" style={{ backgroundImage: "url('/manuscript-page.png')", backgroundSize: 'cover', backgroundPosition: 'center' }} /><div className="relative z-10 max-w-sm"><Quote size={34} className="mb-10 text-accent" /><p className="font-serif text-3xl leading-tight">“Cultivation of mind should be the ultimate aim of human existence.”</p><p className="mt-8 font-mono text-[10px] uppercase tracking-[0.16em] text-primary-foreground/60">B. R. Ambedkar · The Buddha and His Dhamma</p></div><span className="absolute right-6 top-6 font-mono text-[10px] uppercase tracking-[0.16em] text-primary-foreground/50">Folio 01 / 08</span></div>
    </section>
    <section className="border-y border-foreground/10 bg-card/40"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-foreground/10 sm:grid-cols-4"><div className="p-6 lg:p-8"><p className="font-mono text-3xl font-bold">08</p><p className="mt-2 text-xs text-muted-foreground">Featured manuscripts</p></div><div className="p-6 lg:p-8"><p className="font-mono text-3xl font-bold">65+</p><p className="mt-2 text-xs text-muted-foreground">Years of public work</p></div><div className="p-6 lg:p-8"><p className="font-mono text-3xl font-bold">03</p><p className="mt-2 text-xs text-muted-foreground">Primary formats</p></div><div className="p-6 lg:p-8"><p className="font-mono text-3xl font-bold">01</p><p className="mt-2 text-xs text-muted-foreground">Shared reading room</p></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex items-end justify-between gap-5"><div><Eyebrow>Start here</Eyebrow><h2 className="mt-3 text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">A guided way in.</h2></div><Link href="/archive" className="hidden items-center gap-2 text-sm font-semibold text-accent sm:flex">View all records <ArrowRight size={15} /></Link></div><div className="mt-10 grid gap-px bg-foreground/10 md:grid-cols-3">{features.map(([year, title, desc, href]) => <Link key={title} href={href} className="group bg-background p-6 transition-colors hover:bg-muted lg:p-8"><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-accent">{year}</span><ArrowRight size={16} className="text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:text-accent" /></div><h3 className="mt-16 text-2xl font-semibold tracking-[-0.04em]">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{desc}</p></Link>)}</div></section>
    <section className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><Eyebrow>Why this archive</Eyebrow><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em]">Preservation is only the beginning.</h2></div><div className="grid gap-6 sm:grid-cols-3"><div><BookOpen className="text-accent" size={22} /><h3 className="mt-4 font-semibold">Read in context</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/65">Follow ideas across essays, speeches, and time.</p></div><div><FileText className="text-accent" size={22} /><h3 className="mt-4 font-semibold">See the source</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/65">Pair transcriptions with the scanned folio.</p></div><div><Globe2 className="text-accent" size={22} /><h3 className="mt-4 font-semibold">Open to all</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/65">A public reading room without a gate.</p></div></div></div></section>
  </main></ArchiveShell>
}
